### PR TITLE
Add default just recipe, format ts code

### PR DESCRIPTION
**Pull request by hustcer**
Add `default` / `prettier ` and `clean` just recipe, format ts code, run `just` will get:

```shell
Available recipes:
··· build    # Build a release version of Nana
··· clean    # Remove the target directory
··· default  # List available commands by default
··· prettier # Code formatting
··· publish  # Build release version and create an installer/package/bundle
··· setup    # Install node dependencies
··· watch    # Run dev in watch mode
```

### CODE REVIEW

**Comment by fdncred** [comment]
what's the purpose of changing to single quotes?

**Comment by hustcer** [comment]
When in Rome, do as the Romans do, for Rust developers they have to use double quotes, and for Web developers single quote is the preferred choice, just see the [Official React Config](https://github.com/facebook/react/blob/cf665c4b73a28b034c8173f4d929205fb12d2d2e/.prettierrc.js#L7) and [Official Vue Config](https://github.com/vuejs/vue/blob/530b56a36e4689249dce6eba6e5c50e3305346f4/.prettierrc#L2)

**Comment by fdncred** [comment]
interesting. thanks for the explanation.

**Comment by knoopx** [comment]
personally i prefer double quotes. react code style is weird they use single quotes for string literals but double quotes for jsx attributes. i think airbnb style conventions are more popular among react projects. but if you really care about code style i would recommend you to ditch your current setup and just use eslint+some-popular-preset+eslint-prettier instead. also because the current setup forces the same code style for any source code regardless if its javascript or rust and prettier on its own is an inferior formatter compared to the eslint plugin version.

**Comment by hustcer** [comment]
> also because the current setup forces the same code style for any source code regardless if its javascript or rust 

Please do some investigation before you made a conclusion

**Comment by hustcer** [comment]
This PR modified prettier config, but makes no change to `.editorconfig`, and prettier won't touch Rust code

**Comment by knoopx** [comment]
to properly handle two separate coding styles between client/backend we either need to split definitions in `.editorconfig` or to override each `.editorconfig` definition in `.prettierrc`

**Pull request merged**
