### PR TITLE
Update Cargo and Yarn dependencies

### PR DESCRIPTION
**Pull request by jaudiger**
Nothing more. Also, some dependencies haven't been updated yet such Nushell, Reedline, Windows-rs.

### CODE REVIEW

**Comment by fdncred** [comment]
Why are we updating to such an old version? Does it not compile with the latest main for nushell and reedline?

**Comment by jaudiger** [comment]
As for now I’m pinning those versions to the ones from the Cargo lock file. Newer versions of nushell prevent building nana.

I’ll update those dependencies in another MR to isolate the modifications.

**Comment by jaudiger** [comment]
@fdncred do you want I do the update inside this PR ? Or can it wait the next one ?

**Comment by fdncred** [comment]
sorry. let's run with what you've got here.

**Pull request merged**
