### PR TITLE
Switch to yarn/vite/react

### PR DESCRIPTION
**Pull request by knoopx**
hey here's a proposal of changes to further move forward this project. I spent a few hours on this and I think the changes are worth it:

* replaced rollup with vite (which is basically rollup+dev server with hot reloading and convention over configuration). 
* replaced svelte with react and re-implemented all output rendering using small components (instead of concatenating html fragments)
* decoupled the "prompt" from "cards", feels more like a regular terminal now. (ctrl+l clears screen!)
* visual overhaul, using neutral grays for now with contrasting tones to differentiate areas. we can refactor later to add theme support (still using tailwind). shows progress and command execution duration now.
* completion popover!
* fixed some bugs (large image decoding), added some more ~~(history implementation is kind of crappy, would be better to keep a log of executed commands instead of relying on the past results)~~.

some notes:
* there's no sanitization of html (neither was before unless svelte does some magic underneath). we definitely should address this.
* doing several processing steps in the client-side which would be way better to do on rust-side. there's definitely room for improvement on the way we pass data to the client. also all the ansi handling could be greatly improved.
* hex output not implemented
* ~~removed prettier/editorconf/vscode stuff. we can re-introduce if needed but personally I don't like them to be part of projects. (i use all of them but there's really no need to add them as deps if you are using defaults)~~
* I strongly recommend to move state management to mobx-state-tree. you get rendering optimization for free, type-safe data, optional state persistence and development happiness. I can refactor my work if you agree.
* abusive use of `any`, will refactor to use proper types 

please try and let me know what you think before spending more time on this.

### CODE REVIEW

**Comment by fdncred** [comment]
wow, this is a lot of changes and it fundamentally changes everything 'under the hood'. Thanks for taking time to propose your changes. I can see why you kind of want to get approval before moving further. Thanks for this!

I'm trying to figure out how to run this as I'm not a webdev. I did:

1. npm install --global yarn
2. yarn tauri dev and it failed
3. yarn install complains about mixing package managers because package-lock.json was found
4. yarn tauri dev again and it worked this time

> removed prettier/editorconf/vscode stuff. we can re-introduce if needed but personally I don't like them to be part of projects. (i use all of them but there's really no need to add them as deps if you are using defaults)

I personally don't really like that these things were removed, specifically the .editorconfig. please re-add these items.

- Don't like the `$` beside the prompt, it's not bash.
- I like @rgwood's solarized themes better - now it's an odd hybrid but i'm sure that can be tweaked, but the 'neutral grays' are growing on me. :)
- There appear to be some typescript warnings/errors that we'll need to cleanup.

screenshot for those not wanting to check out the build
image

- completions still look nice and work well
- just kind of wow, this is an entire rethinking of what it was, at least what the underlying architecture was - trying to understand vite, do you have a good resource for beginners?

**Comment by knoopx** [comment]
> 1. npm install --global yarn
> 2. yarn tauri dev and it failed
> 3. yarn install complains about mixing package managers because package-lock.json was found
> 4. yarn tauri dev again and it worked this time

that happened because  `package-lock.json` was not under version control (and it should) but it was in your working copy. removing it and running `yarn install` (or simply `yarn`) as you did should fix any problems.

> I personally don't really like that these things were removed, specifically the .editorconfig. please re-add these items.

no prob, restoring them

> * Don't like the `$` beside the prompt, it's not bash.

fair enough, removing them. just wanted a visual indicator to quickly localize command inputs. I can try with just a small colored dot (green/red depending on execution status maybe?)

> * I like @rgwood's solarized themes better - now it's an odd hybrid but i'm sure that can be tweaked, but the 'neutral grays' are growing on me. :)

I can try to implement basic theming support (via console maybe?), with tailwind is easy enough I just don't want to implement a settings UI for now (because that will require more than needed).

> * There appear to be some typescript warnings/errors that we'll need to cleanup.

yeah yeah, plenty of warnings/misusages. just wanted to get this working to show off. ill fix them later©

> * completions still look nice and work well
there's some bugs regarding overflow. current logic is quite stupid. way to go is to use [popper.js ](https://popper.js.org) that does all the overflow calculations properly.

> * just kind of wow, this is an entire rethinking of what it was, at least what the underlying architecture was - trying to understand vite, do you have a good resource for beginners?

the official site [vitejs.dev/ ](https://vitejs.dev) should get you started. there's really not much to learn, has very sensible defaults and it just works©. the default entry point is the index.html at the root, from there it resolves every dependency. there's also [vitest](https://vitest.dev) which I also love. they just take the burden of using multiple web techs.

> * i also like the timer thing "341ns" or whatever the command took

that function was on the code but was unused, just picked it up! I can envision a lot of visual clues if we add support for them on the backend. like full colored output, file icons, thumbnail previews, syntax coloring, preview of markdown files, plotting, etc! it really depends on what we really want to turn this into.

**Comment by fdncred** [comment]
Thanks for your responses @knoopx. For my benefit, could you give some input on why vite/react vs svelte? On your issue, you asked about JSX, but i really didn't realize you were re-architecting the world. :)

**Comment by knoopx** [comment]
well... I didn't expect to go that further either... but had some fun yesterday night 🤣

rollup is a very low level bundler, almost a toolkit. is very flexible but very tedious to configure as every single feature needs to be configured separately. not that you can't but is more targeted at packaging library code rather than full-blown web apps using a mix of different technologies (like typescript/babel/postcss/tailwind, etc..)

vite is very similar to rollup, the plugin api is actually compatible but has several additional features. the main one is the dev server, which is fast because doesnt go through all the bundling pipeline during development, it uses native es modules so theres as least transpilation as possible. also the dev server has proper dependency tracking so it only re-compiles what really changed instead of having to bundle everything every single change. this plus hot reloading makes the development experience very pleasant. the second major feature is sane default configurations. there's barely any need to configure anything unless you want to deviate from best practices or have very weird requirements.

regarding react/svelte here's where the flame war starts 🤣 

this is all very subjective and there's really no perfect framework but here's my 2 cents.

react pros:
* the most popular framework of all time. everyone knows it, everyone used it. everyone can contribute and the ecosystem and community is the biggest with many quality third party libraries.
* modular. react is just a presentation layer. you can mix and match several other non-react specific libraries as you wish. 
* everything is plain, native javascript (yes including JSX, it transpiles to function calls that return virtual dom ast nodes). the virtual dom although adding overhead, allows for greater and more powerful abstraction levels not possible with any other template based frameworks.

react cons:
* not very "reactive" out of the box and the included state management is not great. there are a bunch of awesome alternatives however being https://mobx-state-tree.js.org/intro/welcome my favorite.
* not great error messages (not as bad as typescript)
* not fast and chunky for what it does
* facebook

svelete pros:
* faster pure rendering speed
* small bundles
* great reactive model (but with gotchas like every other reactive system)
* enhanced productivity, as the core provides pretty much everything you need.
* independent, community developed framework 

svelte cons:
* all in one framework. everything, state management, reactivity, animation, rendering is handled by the framework. this is good until the core doesn't do what you need.
* template based with framework specific syntax. mixes style, views and logic (just as vue). for some people this is good. personally i find it like going back to 2000s style of programming when many of your code is contained within strings and passed around/concatenated. parsing/evaluating templates is hard and ambiguous and can be very frustrating for the end user when something does not "compile". although I found svelte error reporting to be very nice.
* way smaller 3rd-party libraries/ecosystem/community.

again this is my personal opinion, but I have plenty of web development experience and tried mostly every framework out there so many of my arguments are a little more than just "i dont like it".

**Comment by jntrnr** [comment]
I'm fine with switching to React. I just chose Svelte because I'd heard good things, though I'd never used it before.

Like @fdncred mentioned, we tend to do things a step at a time. Would it be possible to move to react but keep the design the same? I'm fine moving the bundling step at the same time if that's easier.

This lets us adjust to using React first, and then we can start working on the design improvements (I like the completion popup you added, btw. Nice touch)

**Comment by jntrnr** [comment]
Oh, something else I noticed going back and forth between the two versions - it feels like the React-based one is a little slower than the Svelte one? Not sure why or if I was just seeing things. Ideally, we wouldn't want to lose any performance switching frameworks, though I'm sure some trade-offs are going to happen.

**Comment by fdncred** [comment]
i noticed it was slower on windows too. there's a definite lag like the whole ui is not quite as responsive in a noticeable way.

**Comment by rgwood** [comment]
Thank you for this @knoopx! We're a little light on web dev experience and we could definitely use help in that area.

Agreed with JT that we're OK adopting React but it would be good to break this into smaller changes. On that note, I don't feel strongly about npm vs yarn but maybe changing from npm to yarn should also be considered separately.

I'm trying it on Linux now and it doesn't feel slower than the Svelte version, but I haven't done any benchmarking or anything. Are you aware of any reason why the React implementation might be slower for JT and fdncred?

**Comment by rgwood** [comment]
Hey @knoopx, just wanted to check in and see if you're still keen to work on this.

I think it would be great to adopt React, and we should probably do that before we start work on some upcoming features. If you're not able to get back to this in the next week or so I might be able to do the migration.

**Comment by rgwood** [comment]
OK, I'm noticing some lag on Windows too. 

It might be a Tauri+React bug unrelated to the specifics of this PR; I'm seeing lag even when using the Vite+React+TS Tauri starter template (state updates sometimes take 500ms-1s to be reflected in the UI). However, when I use Vite+React+TS outside Tauri ([the react-ts template](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)) state updates happen immediately.

I can't find any relevant bug reports on the Tauri GitHub or Discord, I might try to put together a minimal reproduction for them.

**Comment by knoopx** [comment]
hey haven't had the time to check but just several points regarding performance:

react/frontend stuff:

* react is significantly slower when running under development mode because it performs several sanity checks, actual performance should be compared using the production bundle
* i'm using array index as key on several looping jsx fragments which is a bad practice as it might trigger unnecessary dom mutations (you should always use a uniq propery within the collection that will never change over time)
* there's some rapid ui changes (a spinner shows while the command is running and prompt/results change position/size) that may affect speed/perception. i also think the code that scrolls window to the bottom is triggering multiple times.
* my fork adds autoprefixer because webkit still needs vendor prefixes for many common stuff and im also using some clever tailwind/css trick ([`default:`](https://github.com/knoopx/nana/blob/main/tailwind.config.js#L32) variant, which allows to set  default properties and override them later without `!` suffix) that might have a significant performance impact on webkit.
* bundle output format and shims can also severely affect browser performance, I recall having better performance while using cjs/regeneratorRuntime than native esm on electron some years ago. haven't really checked this but webkit is not really up to web specs.

backend stuff:

* tauri remote calls are blocking and completely freeze the window (try opening a 50mb binary). not sure if there's a workaround, but ideally these calls should not block interaction and ideally stream the output.
* there's a couple suspicious issues from a few days ago on tauri webview impl (https://github.com/tauri-apps/wry/issues) 
* i'm doing some additional iterations not done in main branch (https://github.com/knoopx/nana/blob/main/src/app/Output.tsx#L94) because I don't fully understand the output structure coming from rust and how it should actually render (a list is presented as a table if all of its items are records or can we assume that if the first is a record the rest are also records?) there's some major render performance to gain if the response from rust contained a property telling the client how to render the data instead of letting the client figure out how (like determining if a binary blob is an image). the current way is going to get worse and worse the more features we add.

**Comment by knoopx** [comment]
pushed more changes, re-based to upstream, fixed build/completion/history, applied some of the suggested changes and made some other improvements. let me know if you see any improvement in responsiveness.

**Comment by rgwood** [comment]
Cool. I'm not seeing any lag on Windows on the latest commit. Would be good if JT or fdncred can confirm too.

**Comment by knoopx** [comment]
added basic theming support, change themes by invoking `localStorage.theme = "mytheme"`. You can use any of the predefined themes in https://daisyui.com/docs/themes/

**Comment by rgwood** [comment]
@knoopx Cool! Theming sounds great but this is taking us further away from 1-change-at-a-time:

> we tend to do things a step at a time. Would it be possible to move to react but keep the design the same?

>  it would be good to break this into smaller changes.

I think this PR currently has a number of distinct changes:

1. Change from Svelte to React
2. Overhaul the design (different colours, no longer using the "card" design metaphor)
3. Switch from npm to yarn
4. Add completion
5. Add theming support
6. Removed the justfile

I think we're agreed that many of those are great changes, but this is getting to be a lot for 1 PR. Are you planning on breaking up the changes (either in this PR or a new one)?

**Comment by knoopx** [comment]
I can understand you being overwhelmed by the amount of changes, I can try to split the PR into atomic commits so you can see them individually but will take me some time

**Comment by fdncred** [comment]
> I can try to split the PR into atomic commits...

Thanks so much @knoopx ❤️

**Comment by knoopx** [comment]
just pushed more changes, some additional comments:
 
yarn vs npm: 
* simpler command interface
* parallel downloads
* `yarn upgrade -L`
* `yarn release`
* resolves merge conflicts on `yarn.lock`
* no need to `rm -R node_modules` from time to time 

just/justfile provides no value unless I'm missing context. it just forwards commands to npm/yarn but they already provide project-scoped tasks via `scripts` in `package.json`. I've migrated all tasks defined in the justfile, you can just run `yarn <previous just task>` and effectively run the same commands.

**Comment by rgwood** [comment]
Thanks for organizing this by commit. I would vote to leave theming out of this PR; it adds a dependency and I think it will be easier to iterate on Nana without that abstraction for now.

**Comment by knoopx** [comment]
split the react rewrite/ui changes into a separate commit and removed the theming stuff. should be clear what every change introduces now. stopping working on this until we set a common ground and possibly revisit back-end communication.

**Comment by knoopx** [comment]
@rgwood my latest push included a separate commit for just the react port https://github.com/nushell/nana/pull/32/commits/f98230d85c4c4ea69326d7e2e2a22a223c334592. you can checkout that specific commit and try in separation of my ui changes

**Comment by fdncred** [comment]
@rgwood I've tried a few different commits. If we're looking at f98230d then i see the tiniest lag when doing `$nu<enter>` with `yarn tauri dev` and `yarn tauri build` but `$nu` is massive. so, i'm not sure that's a big concern atm. everything else i tested seemed pretty close to the same perf anecdotally.

**Comment by jntrnr** [comment]
@rgwood - performance looks good to me. Seem basically identical on my mac for a release build.

**Comment by rgwood** [comment]
Fantastic! @knoopx, we'd be happy to merge https://github.com/nushell/nana/commit/f98230d85c4c4ea69326d7e2e2a22a223c334592. Many thanks for your hard work, this is a big step forward for Nana.

Are you able to update the PR to that commit (either by reverting or deleting  https://github.com/nushell/nana/pull/32/commits/e2742e349e495a6dad80599bad5075eaafb44a3e)?

**Comment by knoopx** [comment]
pushed again, PR now only contains yarn/vite/react port. keep in mind the port is not 1:1 and some functionality are not implemented (like hex output). also the card ux has several inconsistencies that aren't fully solved:

* can you add cards? if so how?
* what should happen when you submit a card? 
* can you edit previous cards? what should happen when you replace the command and submit?
* can you delete all cards? what should happen when you delete all cards? 
  * original impl simply deletes everything and you can no longer input any command
  * react impl adds auto-adds new empty card when deleting them all

**Comment by rgwood** [comment]
I think we're ready to merge, future improvements can be done in separate PRs. Thanks for the huge contribution!

**Pull request merged**
