### PR TITLE
Implement save file functionality

### PR DESCRIPTION
**Pull request by rgwood**
Add a simple button and dropdown menu to save the contents of a card. Lots of screenshots:

image

image

image

We use the OS's native file picker and message box:

image

image

## Future work

- Generalize the dropdown so we can use it for other things too?
- Add keyboard shortcut
    - will probably be a rabbit hole, haven't thought much about shortcuts yet

### CODE REVIEW

**Comment by fdncred** [comment]
@rgwood Can't get it to show the save dialog on my Mac. The main windows goes dark like there is a popped up save dialog but it doesn't show up for me. I also get warnings on compile.
```
warning: unused imports: `MenuItem`, `Menu`, `Submenu`
  --> src/main.rs:21:13
   |
21 | use tauri::{Menu, MenuItem, Submenu};
   |             ^^^^  ^^^^^^^^  ^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `nana` (bin "nana") generated 1 warning
```

**Comment by rgwood** [comment]
That's surprising that it doesn't work on macOS; might be a bug in Tauri, I'm using their file picker API.

I think those warnings are probably from another PR I did recently. I'll try to get cargo fmt/clippy working in CI to catch warnings like that.

**Comment by fdncred** [comment]
I got it to work. It may be some weird edge case. If I stay on the virtual desktop while it's building and wait for it to pop up with `just watch`, it works.  If I switch to another virtual desktop while it's building and then it pops up on a different virtual desktop, the dialog doesn't pop up on any virtual desktop. It's just weird.

I also noticed that when I got it to work, it defaulted to a save folder that wasn't the folder that I was in. i.e. I ran just watch from the nana folder and the save dialog was in the nushell folder. I wonder if that's just where the save dialog was at last time from some other app?

**Comment by rgwood** [comment]
> I also noticed that when I got it to work, it defaulted to a save folder that wasn't the folder that I was in. i.e. I ran just watch from the nana folder and the save dialog was in the nushell folder. I wonder if that's just where the save dialog was at last time from some other app?

Good question, I'm not sure how Tauri (or the OS?) chooses the starting folder when you don't specify it. We might want to specify it eventually.

**Pull request merged**
